Новая версия.
bazhenov/aot-lematizer pull request #11
Opened 2019-08-02 01:04 UTC by demidko

Исправлена проблема коллизий хеша. Скорость не просела..

2019-08-07 07:15 UTC, bazhenov requested changes

2019-08-07 07:15 UTC, bazhenov commented on compiler/src/main/java/com/farpost/aot/mrd/Flexion.java
> +public class Flexion {
У нас два класса с таким именем. Можем мы их как-то удачней назвать?

2019-08-07 07:15 UTC, bazhenov commented on compiler/src/main/java/com/farpost/aot/mrd/Mod.java
> +	public Mod(final String postfix, final int infoIndex, final String prefix) {
Давай писать `final` только там, где неизменность переменной действительно имеет значение (например, на полях класса). В этом конструкторе все аргументы просто копируются в свойства объекта. При этом даже изменение объектов внутри конструктора, не может поменять ссылку снаружи. Повсеместное использование `final` только затрудняет чтение и ничего не добавляет.

2019-08-07 07:15 UTC, bazhenov commented on compiler/src/main/java/com/farpost/aot/mrd/Paradigm.java
> +	public Paradigm(final List<Mod> mods) {
Конструктор должен быть первый после свойств

2019-08-07 07:15 UTC, bazhenov commented on compiler/src/main/java/com/farpost/aot/Utils.java
> +	public static int hashFromString(final String input) {
Чем обусловлено наличие этого метода? Почему ты не используешь `str.hashCode()`?

2019-08-07 07:15 UTC, bazhenov commented on compiler/src/main/java/com/farpost/aot/Utf8ResourceReader.java
> +	public void close() throws IOException {
Если этот класс тоже должен корректно закрываться клиентом, то он должен имплементировать `Closeable`

2019-08-07 07:15 UTC, bazhenov commented on compiler/src/main/java/com/farpost/aot/Main.java
> +	public static void main(final String[] args) throws IOException {
Давай класс `Compilation` и сделаем main-классом

2019-08-07 07:15 UTC, bazhenov commented on compiler/src/main/java/com/farpost/aot/Utf8ResourceReader.java
> +public abstract class Utf8ResourceReader {
Давай избавимся от этого класса, если это возможно. Он не выполняет никакой полезной работы, помимо обертки на `BufferedReader`'ом

2019-08-07 07:15 UTC, demidko commented on compiler/src/main/java/com/farpost/aot/Main.java
> +	public static void main(final String[] args) throws IOException {
Ок

2019-08-07 07:16 UTC, bazhenov requested changes

2019-08-07 07:16 UTC, bazhenov commented on library/src/main/java/com/farpost/aot/func/Decompiler.java
> +		return b == 100;
Так 95 или 100?

2019-08-07 07:24 UTC, demidko commented on library/src/main/java/com/farpost/aot/func/Decompiler.java
> +		return b == 100;
100, 95и уже нигде нет.

2019-08-07 07:27 UTC, demidko commented on compiler/src/main/java/com/farpost/aot/Utils.java
> +	public static int hashFromString(final String input) {
не актуально.

2019-08-07 07:27 UTC, demidko commented on compiler/src/main/java/com/farpost/aot/mrd/Paradigm.java
> +	public Paradigm(final List<Mod> mods) {
не актуально

2019-08-07 07:27 UTC, demidko commented on compiler/src/main/java/com/farpost/aot/mrd/Mod.java
> +	public Mod(final String postfix, final int infoIndex, final String prefix) {
не актуально

2019-08-07 07:28 UTC, demidko commented on compiler/src/main/java/com/farpost/aot/mrd/Flexion.java
> +public class Flexion {
не актуально

2019-08-12 01:23 UTC, bazhenov requested changes

2019-08-12 01:23 UTC, bazhenov commented on library/src/main/java/com/farpost/aot/data/GrammarInfo.java
> +public enum GrammarInfo {
теги связанные с частью речи (POS) выделить в отдельный enum и сделать getter в `FlexionInfo`

2019-08-12 01:23 UTC, bazhenov commented on benchmark/pom.xml
> +	<artifactId>bencmark</artifactId>
Давай `artifactId` поднимем наверх (сразу после тега `parent`), а то один из ключевых тегов (имя модуля) в самом конце файла.

2019-08-12 01:23 UTC, bazhenov commented on benchmark/src/main/java/com/farpost/aot/LookupBenchmark.java
> +		String nextWord;
Поля можно сделать `private`

2019-08-12 01:23 UTC, bazhenov commented on compiler/pom.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Нарушено форматирование. Проверь настройки IDE.

2019-08-12 01:23 UTC, bazhenov commented on compiler/src/main/java/com/farpost/aot/CollisionsFilter.java
> +	public static class Result {
Даже если у класса все свойства `final` лучше getter'ы все равно выделять и замыкать доступ через них.

2019-08-12 01:23 UTC, bazhenov commented on compiler/src/main/java/com/farpost/aot/CollisionsFilter.java
> +			.collect(Collectors.toSet())
Старайся использовать все возможности языка, которые позволяют делать код менее многословным. В данном случае, очень уместен static import – `.collect(toSet())`.

2019-08-12 01:23 UTC, bazhenov commented on compiler/src/main/java/com/farpost/aot/CollisionsFilter.java
> +	private static boolean isCollision(List<Flexion> flexionsWithOneHash) {
Здесь достаточно `Collection`. В аргументах лучше использовать настолько общие типы, насколько это позволяет контракт.

2019-08-12 01:23 UTC, bazhenov commented on compiler/src/main/java/com/farpost/aot/CollisionsFilter.java
> +				.computeIfAbsent(i.source.hashCode(), k -> new ArrayList<>())
Если контрольная сумма флексии настолько важна для словаря, я думаю стоит выделить отдельный метод в `Flexion` для этой задачи.

2019-08-12 01:23 UTC, bazhenov commented on compiler/src/main/java/com/farpost/aot/Compiler.java
> +		final var store = new FlexionStorage();
Не нужно пихать `final` в каждую локальную переменную. Это затрудняет чтение кода, ставь там где это действительно важно.

2019-08-12 01:23 UTC, bazhenov commented on compiler/src/main/java/com/farpost/aot/Compiler.java
> +	public static void main(String[] args) throws IOException {
Этот метод читается крайне сложно. Перепиши его, разбив на методы таким образом, чтобы по коду были ясны отдельные фазы компиляции.

2019-08-12 01:23 UTC, bazhenov commented on compiler/src/main/java/com/farpost/aot/Compiler.java
> +		System.out.println(String.format("Извлечено колизионных флексий %d", removed.size()));
Все комментарии должны быть на английском. Агрессивней используй static import. Много лишних упоминаний классов

2019-08-12 01:23 UTC, bazhenov commented on compiler/src/main/java/com/farpost/aot/Compiler.java
> +			res[i] = (byte) Arrays.binarySearch(GrammarInfo.values(), line.get(i));
Если ты здесь результат кастишь к byte, то было бы неплохо сначала проверить размер массива.

2019-08-12 01:23 UTC, bazhenov commented on library/pom.xml
> +<project xmlns="http://maven.apache.org/POM/4.0.0"
Давай явно укажем компилятору, что этот модуль должен быть собран под java 1.8. Иначе результат, насколько я понимаю, может зависеть от того на какой JVM собирается проект.

2019-08-12 01:23 UTC, bazhenov commented on library/src/main/java/com/farpost/aot/LemmaDictionary.java
> +			boolean notFound = true;
Булевые переменные без отрицания в имени проще поддаются понимаю.

2019-08-12 01:23 UTC, bazhenov commented on library/src/main/java/com/farpost/aot/data/FlexionInfo.java
> +	public boolean isNot(final GrammarTag... info) {
Более удачное название для метода `notAnyOf`

2019-08-12 01:23 UTC, bazhenov commented on library/src/main/java/com/farpost/aot/data/FlexionInfo.java
> +public class FlexionInfo {
Нужно выделить так же как и `PartOfSpeech` информацию о:

* роде;
* числе;
* падеже;
* одушевленности.

2019-08-12 01:23 UTC, bazhenov commented on library/src/main/java/com/farpost/aot/data/GrammarTag.java
> +public enum GrammarTag {
Корректней назвать `MorphologyTag`, так как все эти признаки морфологические, а не грамматические.

2019-08-12 01:23 UTC, bazhenov commented on library/src/main/java/com/farpost/aot/data/LemmaInfo.java
> +	public final String lemma;
getter!

2019-08-12 01:43 UTC, bazhenov requested changes

2019-08-12 01:43 UTC, bazhenov commented on library/src/main/java/com/farpost/aot/data/LemmaInfo.java
> +		this.lemma = lemma;
`requireNonNull`

2019-08-12 01:43 UTC, bazhenov commented on library/src/main/java/com/farpost/aot/data/PartOfSpeech.java
> +public enum PartOfSpeech {
А зачем нам аналогичные теги в `GrammarInfo`? Можем ли мы обойтись одним enum'ом?

2019-08-12 01:43 UTC, bazhenov commented on library/src/main/java/com/farpost/aot/func/Decompiler.java
> +	// оптимизация чтобы не выделять каждый раз память под буфер юникодных символов
Комментарии надо писать через
```
/**
 *
 */
```

Тогда они корректно показываются средой по Ctrl+J

2019-08-12 01:43 UTC, bazhenov commented on library/src/main/java/com/farpost/aot/func/Decompiler.java
> +	private static final char[] resultBuffer = new char[36];
Что произойдет с этим кодом если словарь будет использоваться в многопоточной среде?

2019-08-12 01:52 UTC, demidko commented on benchmark/pom.xml
> +	<artifactId>bencmark</artifactId>
исправил

2019-08-12 01:54 UTC, demidko commented on benchmark/src/main/java/com/farpost/aot/LookupBenchmark.java
> +		String nextWord;
сделал

2019-08-12 02:14 UTC, bazhenov requested changes

2019-08-12 02:14 UTC, bazhenov commented on library/src/main/java/com/farpost/aot/func/Decompiler.java
> +		return b == 100;
Но у тебя осталось дублирование с `com.farpost.aot.Compiler.byteFromChar()`

2019-08-12 02:14 UTC, bazhenov commented on library/src/main/java/com/farpost/aot/storages/CollisionFlexionStorage.java
> +			final byte[] strbuf = new byte[36];
"Магические числа" должны быть выделены в константы с описанием

2019-08-12 02:14 UTC, bazhenov commented on library/src/main/java/com/farpost/aot/storages/CollisionFlexionStorage.java
> +			final String javaString = stringFromBytes(Arrays.copyOf(strbuf, strbufIndex + 1));
Вроде, тут можно без копирования обойтись

2019-08-12 02:14 UTC, bazhenov commented on library/src/main/java/com/farpost/aot/storages/GrammarStorage.java
> +			for (byte currentByte = reader.readByte(); !isEndl(currentByte); currentByte = reader.readByte()) {
Дублирование. Аналогичный код в `CollisionFlexionStorage`

2019-08-12 02:14 UTC, bazhenov commented on library/src/main/java/com/farpost/aot/storages/LemmaStorage.java
> +		/*lines = new byte[reader.readInt()][];
Мертвый код нужно удалять

2019-08-12 02:14 UTC, bazhenov commented on library/src/main/java/com/farpost/aot/storages/NormalFlexionStorage.java
> +	private static int intFromBytes(byte a, byte b, byte c, byte d) {
Судя по использованию, какой-то неудобный helper. Можешь придумать более подходящий контракт исходя из контекста использования метода?

2019-08-12 02:14 UTC, bazhenov commented on library/src/test/java/com/farpost/aot/LemmaDictionaryTest.java
> +		assertThat(d.lookup("краснеющий").size(), is(1));
Есть более подходящий matcher `hasSize()`

2019-08-12 02:14 UTC, bazhenov commented on library/src/test/java/com/farpost/aot/LemmaDictionaryTest.java
> +	public LemmaDictionaryTest() throws IOException {
Бесполезный конструктор

2019-08-12 02:14 UTC, bazhenov commented on loader/pom.xml
> +		<dependency>
тестовые зависимости полезно определять один раз в родительском проекте

2019-08-12 02:14 UTC, bazhenov commented on loader/src/main/java/com/farpost/aot/FlexionStorage.java
> +				for (final var j : flex) {
То же самое можно сделать более "идиоматично":

```
String lemmas = flex.stream()
  .map(Flexion::getSource)
  .collect(joining(" "));
out.println(lemmas);
```

2019-08-12 02:14 UTC, bazhenov commented on loader/src/main/java/com/farpost/aot/FlexionStorage.java
> +					System.out.print(' ');
Если ты часто используешь `System.out`, то можно сделать static import.

2019-08-12 02:14 UTC, bazhenov commented on loader/src/main/java/com/farpost/aot/func/Mod.java
> +	public Flexion apply(final String base) {
Очень похоже на функциональное API. Может стоит ли имплементировать `Function`?

2019-08-12 02:14 UTC, bazhenov commented on loader/src/main/java/com/farpost/aot/readers/TabReader.java
> +public class TabReader {
Не очень удачное, на мой взгляд, разделение ответственностей. Единственный клиент `TabReader` – `GrammarStorage`. И он потом начинает парсить содержимое `tab` файла из строки. Почему бы это не сделать здесь?

2019-08-12 02:14 UTC, bazhenov commented on loader/src/main/java/com/farpost/aot/storages/ParadigmStorage.java
> +							new Mod(infoIndex, args[2].toLowerCase().replace('ё', 'е'), postfix);
Дублирование обработки буквы ё

2019-08-12 02:14 UTC, bazhenov commented on loader/src/main/java/com/farpost/aot/storages/ParadigmStorage.java
> +						final var args = src.split("\\*");
Давай выделим это замыкание в отдельный метод. Слишком сложный pipeline уже получается

2019-08-12 02:14 UTC, bazhenov commented on testapp/src/main/java/com/farpost/aot/TestApplication.java
> +			while (true) {
Это не важно в данном случае, поэтому исправлять не обязательно, но может быть тебе будет полезно знать.

Лучше вечные циклы заменять на:

```
while (currentThread().isInterrupted()) {

}
```

Это позволяет прерывать такие циклы извне. В противном случае может оказаться так (зависит от того как создавался поток), что единственный способ остановить приложение - `kill -9`.

2019-08-12 02:30 UTC, demidko commented on compiler/src/main/java/com/farpost/aot/CollisionsFilter.java
> +				.computeIfAbsent(i.source.hashCode(), k -> new ArrayList<>())
Написал тест сравнивающий хеши jvm8 и jvm11 (эквивалентны)

2019-08-12 03:05 UTC, demidko commented on compiler/src/main/java/com/farpost/aot/Compiler.java
> +	public static void main(String[] args) throws IOException {
Готово

2019-08-12 03:06 UTC, demidko commented on compiler/src/main/java/com/farpost/aot/Compiler.java
> +		final var store = new FlexionStorage();
Ок

2019-08-12 03:07 UTC, demidko commented on compiler/src/main/java/com/farpost/aot/Compiler.java
> +			res[i] = (byte) Arrays.binarySearch(GrammarInfo.values(), line.get(i));
Проверял, он меньше чем 90

2019-08-14 03:14 UTC, demidko commented on compiler/src/main/java/com/farpost/aot/Compiler.java
> +			res[i] = (byte) Arrays.binarySearch(GrammarInfo.values(), line.get(i));
Добавил проверку

2019-08-14 03:14 UTC, demidko commented on library/pom.xml
> +<project xmlns="http://maven.apache.org/POM/4.0.0"
в родительском POM прописана компиляция под JVM 8, поэтому дочерний наследует это указание

2019-08-14 03:14 UTC, demidko commented on library/src/main/java/com/farpost/aot/LemmaDictionary.java
> +			boolean notFound = true;
ок

2019-08-14 03:14 UTC, demidko commented on library/src/main/java/com/farpost/aot/storages/CollisionFlexionStorage.java
> +			final String javaString = stringFromBytes(Arrays.copyOf(strbuf, strbufIndex + 1));
Исправил

2019-08-14 03:14 UTC, demidko commented on library/src/main/java/com/farpost/aot/storages/NormalFlexionStorage.java
> +	private static int intFromBytes(byte a, byte b, byte c, byte d) {
ок

2019-08-14 03:14 UTC, demidko commented on library/src/test/java/com/farpost/aot/LemmaDictionaryTest.java
> +	public LemmaDictionaryTest() throws IOException {
Он нужен т. к. 
private final LemmaDictionary d = new LemmaDictionary();
Выкидывает прописанный в конструкторе эксцепшн

2019-08-14 03:14 UTC, demidko commented on library/src/main/java/com/farpost/aot/data/PartOfSpeech.java
> +public enum PartOfSpeech {
Не можем, тогда поломается декомпиляция, которая сейчас построена на том что каждый байт является порядковым номером соответствующего элемента MorphologyTag. 
У элементов PartOfSpeech другие порядковые номера. 
Если мы захотим разделить эти перечисления на этапе считывания, то усложним код + просядет скорость загрузки.
Если захотим разделить их на этапе компиляции, то и усложним компиляцию и скорость загрузки опять таки просядет.

2019-08-14 03:14 UTC, demidko commented on compiler/src/main/java/com/farpost/aot/CollisionsFilter.java
> +	public static class Result {
ок готово

2019-08-14 03:14 UTC, demidko commented on library/src/main/java/com/farpost/aot/data/FlexionInfo.java
> +public class FlexionInfo {
Невозможно одназначено выделить ни один из этих признаков

2019-08-14 05:19 UTC, bazhenov commented on library/src/main/java/com/farpost/aot/LemmaDictionary.java
> +	private final NormalFlexionStorage norFlex;
Предлагаю перенести `CollisionFlexionStorage` и `NormalFlexionStorage` в пакет `com.farpost.aot`. Это позволит сделать эти классы package-local. Им совсем не обязательно быть публичными.

2019-08-14 05:23 UTC, bazhenov commented on library/src/main/java/com/farpost/aot/data/LemmaInfo.java
> +	public String toString() {
```
String flexions = this.flexions.stream()
    .map(Object::toString)
    .collect(joining(", "));
return String.format("<%s %s>", lemma, flexions);
```

Согласись проще читается

2019-08-14 05:25 UTC, bazhenov commented on library/src/main/java/com/farpost/aot/data/FlexionInfo.java
> +	 * @return список тегов
В таких случаях вполне уместно совмещать основной блок описания и тег `@return`. Т.е.

```
/**
 * @return множество морфологических тегов
 */
```

2019-08-14 05:26 UTC, bazhenov commented on library/src/main/java/com/farpost/aot/data/FlexionInfo.java
> +	public List<MorphologyTag> getAllTags() {
Может уместней сделать возвращаемое значение `Set<MorphologyTag>`?

2019-08-14 05:28 UTC, bazhenov commented on library/src/main/java/com/farpost/aot/func/Decompiler.java
> +	 * @throws IOException
Пустые теги никому не нужны, они не добавляют информации и их не следует писать.

2019-08-14 05:28 UTC, bazhenov commented on library/src/main/java/com/farpost/aot/func/Decompiler.java
> +	private static final MorphologyTag[] grmBuf = new MorphologyTag[12];
Поля выше методов

2019-08-14 23:45 UTC, demidko commented on library/src/main/java/com/farpost/aot/LemmaDictionary.java
> +	private final NormalFlexionStorage norFlex;
Готово

2019-08-14 23:49 UTC, demidko commented on library/src/main/java/com/farpost/aot/data/FlexionInfo.java
> +	 * @return список тегов
Ок, готово

2019-08-20 01:44 UTC, closed without merging